import Foundation
import Security
import ServiceManagement

@objc protocol LiberatorHelperProtocol {
    func apply(_ payload: Data, authorization: Data, withReply reply: @escaping (Data?, String?) -> Void)
}

// Generated by build.sh for a Developer ID release. Local builds fail closed for root operations.


final class AdminAuthorization {
    private var reference: AuthorizationRef?
    init() throws {
        var ref: AuthorizationRef?
        guard AuthorizationCreate(nil, nil, [], &ref) == errAuthorizationSuccess, let ref else { throw POSIXError(.EACCES) }
        reference = ref
        let status = "system.privilege.admin".withCString { name -> OSStatus in
            var item = AuthorizationItem(name: name, valueLength: 0, value: nil, flags: 0)
            return withUnsafeMutablePointer(to: &item) { pointer in
                var rights = AuthorizationRights(count: 1, items: pointer)
                return AuthorizationCopyRights(ref, &rights, nil, [.interactionAllowed, .extendRights], nil)
            }
        }
        guard status == errAuthorizationSuccess else { throw NSError(domain: NSOSStatusErrorDomain, code: Int(status)) }
    }
    func externalForm() throws -> Data {
        guard let reference else { throw POSIXError(.EACCES) }
        var form = AuthorizationExternalForm()
        guard AuthorizationMakeExternalForm(reference, &form) == errAuthorizationSuccess else { throw POSIXError(.EACCES) }
        return withUnsafeBytes(of: &form) { Data($0) }
    }
    deinit { if let reference { AuthorizationFree(reference, [.destroyRights]) } }
}

@MainActor
final class PrivilegedClient {
    private let service = SMAppService.daemon(plistName: serviceName + ".plist")
    var status: SMAppService.Status { service.status }
    var releaseEnabled: Bool { !BuildIdentity.teamID.isEmpty }
    func register() throws {
        guard releaseEnabled else {
            throw NSError(domain: "Liberator", code: 20, userInfo: [NSLocalizedDescriptionKey: "Administrator cleanup requires a Developer ID signed and notarized release. This local build supports your own files and apps through macOS App Management."])
        }
        try service.register()
    }
    func unregister() async throws { try await service.unregister() }
    func apply(_ requests: [ChangeRequest], authorization: AdminAuthorization) async throws -> [ChangeOutcome] {
        guard releaseEnabled && status == .enabled else { throw POSIXError(.EACCES) }
        let connection = NSXPCConnection(machServiceName: serviceName, options: .privileged)
        connection.remoteObjectInterface = NSXPCInterface(with: LiberatorHelperProtocol.self)
        connection.setCodeSigningRequirement("anchor apple generic and certificate leaf[subject.OU] = \"\(BuildIdentity.teamID)\" and identifier \"\(serviceName)\"")
        connection.resume()
        defer { connection.invalidate() }
        let data = try JSONEncoder().encode(requests)
        let auth = try authorization.externalForm()
        // A timeout must also settle the continuation if the daemon exits without replying.
        return try await withCheckedThrowingContinuation { continuation in
            let gate = ReplyGate(continuation)
            connection.invalidationHandler = { gate.fail("The administrator helper disconnected.") }
            connection.interruptionHandler = { gate.fail("The administrator helper was interrupted.") }
            guard let proxy = connection.remoteObjectProxyWithErrorHandler({ error in gate.fail(error.localizedDescription) }) as? LiberatorHelperProtocol else { gate.fail("Administrator helper unavailable."); return }
            proxy.apply(data, authorization: auth) { response, error in
                if let error { gate.fail(error); return }
                do { gate.succeed(try JSONDecoder().decode([ChangeOutcome].self, from: response ?? Data())) }
                catch { gate.fail(error.localizedDescription) }
            }
            DispatchQueue.global().asyncAfter(deadline: .now() + 60) { gate.fail("Administrator cleanup timed out. Rescan before retrying.") }
        }
    }
}

final class ReplyGate: @unchecked Sendable {
    let lock = NSLock()
    var continuation: CheckedContinuation<[ChangeOutcome], Error>?
    init(_ value: CheckedContinuation<[ChangeOutcome], Error>) { continuation = value }
    func succeed(_ result: [ChangeOutcome]) { finish(.success(result)) }
    func fail(_ message: String) { finish(.failure(NSError(domain: "Liberator", code: 21, userInfo: [NSLocalizedDescriptionKey: message]))) }
    private func finish(_ result: Result<[ChangeOutcome], Error>) {
        lock.lock(); let c = continuation; continuation = nil; lock.unlock(); c?.resume(with: result)
    }
}
